import { createHash } from 'node:crypto';

// Bucket ids are a global namespace across this Supabase project, not
// scoped per schema — content-engine-* prefix avoids any collision with
// bgrowth-portal's own portal-product-assets bucket. Created manually in
// the Supabase dashboard (Storage buckets aren't provisioned by SQL
// migrations); not created by this code.
export const CREATIVE_ASSETS_BUCKET = 'content-engine-creative-assets';

const EXTENSION_BY_MIME = {
  'image/png': 'png',
  'image/jpeg': 'jpg',
  'image/webp': 'webp',
};

/**
 * Uploads a generated creative asset to Supabase Storage and returns
 * everything needed to persist a content_engine.creative_assets row.
 * storage_path is the permanent identifier; public_url is always DERIVED
 * from it via getPublicUrl(path) here, never treated as independently
 * authoritative elsewhere — see the Phase 2F-A storage refinement audit.
 *
 * Path convention: {content_item_id}/{asset_id}.{extension} — both
 * segments are already-stable UUIDs, so the path never needs to change if
 * any other field (asset_type, created_at) is later corrected. assetId is
 * generated by the caller (api/content-engine/creative-assets.js) BEFORE
 * this upload, specifically so the same id can be used both for the
 * Storage path and, afterward, as the creative_assets row's own primary
 * key — required because upload must happen before the database row
 * exists (see that file's upload-before-insert ordering).
 */
export async function uploadCreativeAsset(supabase, { contentItemId, assetId, buffer, mimeType }) {
  const extension = EXTENSION_BY_MIME[mimeType] ?? 'bin';
  const path = `${contentItemId}/${assetId}.${extension}`;

  const { error } = await supabase.storage.from(CREATIVE_ASSETS_BUCKET).upload(path, buffer, {
    contentType: mimeType,
    upsert: false,
  });
  if (error) throw error;

  const { data } = supabase.storage.from(CREATIVE_ASSETS_BUCKET).getPublicUrl(path);
  const checksum = createHash('sha256').update(buffer).digest('hex');

  return { path, url: data.publicUrl, mimeType, sizeBytes: buffer.byteLength, checksum };
}

/**
 * Deletes a stored creative asset's underlying Storage object only — never
 * touches the database row. Callers decide row lifecycle separately: the
 * DELETE handler removes the Storage object FIRST and only deletes the row
 * once that succeeds (so a failed Storage delete never leaves a row
 * pointing at nothing); the POST handler calls this as a best-effort
 * compensating action if the database insert fails after a successful
 * upload, logging (not throwing) if the cleanup itself fails so the
 * caller's original, more important error is never masked.
 */
export async function deleteCreativeAssetFile(supabase, path) {
  const { error } = await supabase.storage.from(CREATIVE_ASSETS_BUCKET).remove([path]);
  if (error) throw error;
}
